const enumeratorData = {
    'EN01': {name:'Kayoed B.O.Stella'},
    'EN02': {name:'Sincomoh Neat'},
    'EN03': {name:'Odeh Stephina Ebiperemene'},
    'EN04': {name:'Ogodo Charles'},
    'EN05': {name:'Egba I.Prince'},
    'EN06': {name:'Eric Ebidoubo Pabai'},
    'EN07': {name:'Iwaeni Tonbra Muyin'},
    'EN08': {name:'TimiTimi Pere Davide'},
    'EN09': {name:'Renner Emmanuel'},
    'EN10': {name:'Dickson Ebipre'},
    'EN11': {name:'Odum Ebimobowei Harrison'},
    'EN12': {name:'Ambrose A. Williams'},
    'EN13': {name:'Joel Boniface Wilson'},
    'EN14': {name:'Egbe Samson Tamarauem'},
    'EN15': {name:'Victor Clement Yenevie'},
    'EN16': {name:'Daniel Friday Biteboye'},
    'EN17': {name:'Ojike Nneoma Sandra'},
    'EN18': {name:'Emmanuel Isaac'},
    'EN19': {name:'David Briggs'},
    'EN20': {name:'Deric Emmanuel Otonbara'},
    'EN21': {name:'Samson Ebilakpo'},
    'EN22': {name:'Newman Freedom'},
    'EN23': {name:'Greatness Kolowei'},
    'EN24': {name:'Dollar Gabrielle'},
    'EN25': {name:'Rufus Princewill'},
    'EN26': {name:'Deinghan Theophilus'},
    'EN27': {name:'Kontei James Agiari'},
    'EN28': {name:'Eki Blessing'},
    'EN29': {name:'Duate Renner'},
    'EN30': {name: 'Ebogho Samuel Godwill'},
    'EN31': {name: 'Alexander Erenanyo'},
    'EN32': {name: 'Fredrick Ebilade'},
    'EN33': {name: 'Ifeanyi Onwubu'},
    'EN34': {name: 'Agiari Nanabotonghen James'},
    'EN35': {name: 'Tariere Alfred'},
    'EN36': {name: 'Laye Abali'},
}

export default enumeratorData;